# Generated by Django 3.1.4 on 2020-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.AddField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
